version: "3.9"

services:
  db_dev:
    image: postgres:15
    restart: always
    env_file: .env.db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql

volumes:
  movies_data_dev: