apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    tier: backend
    app: moviesapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081