apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: moviesapp
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000