apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviesapp
      tier: frontend
  template:
    metadata:
      labels:
        app: moviesapp
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: konstantinosal/kubernetes-movies-frontend-service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BACKEND_HOST
