apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: moviesapp
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: konstantinosal/kubernetes-movies-frontend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BACKEND_HOST
